In [1]:
import pandas as pd
import numpy as np

In [2]:
county_pr = pd.read_csv(r"C:\Users\SEKAR\Desktop\Raw data\Cook_County_Payroll\Cook_County_Payroll_Raw.csv")

county_pr.head()

,Fiscal Year,Fiscal Quarter,Fiscal Period,First Name,Last Name,Middle Init,Bureau,Office,Office Name,Job Code,Job Title,Base Pay,Position ID,Employee Identifier,Original Hire Date
0,2016,1,2016Q1,AMRITH,AAKRE,K,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$20,088.00",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
1,2016,2,2016Q2,AMRITH,AAKRE,K,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$23,436.00",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
2,2016,3,2016Q3,AMRITH,AAKRE,K,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$20,422.82",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
3,2016,4,2016Q4,AMRITH,AAKRE,K,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$23,904.80",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
4,2017,1,2017Q1,AMRITH,AAKRE,K,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$20,745.80",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005

In [3]:
county_pr.dtypes

Fiscal Year              int64
Fiscal Quarter           int64
Fiscal Period           object
First Name              object
Last Name               object
Middle Init             object
Bureau                  object
Office                 float64
Office Name             object
Job Code                 int64
Job Title               object
Base Pay                object
Position ID              int64
Employee Identifier     object
Original Hire Date      object
dtype: object

In [4]:
county_pr.shape

(234299, 15)

In [5]:
county_pr.duplicated().sum()

np.int64(0)

In [6]:
county_pr.isnull().sum()

Fiscal Year                0
Fiscal Quarter             0
Fiscal Period              0
First Name                 0
Last Name                  0
Middle Init            93412
Bureau                     0
Office                  3184
Office Name             3184
Job Code                   0
Job Title                  0
Base Pay                   4
Position ID                0
Employee Identifier        0
Original Hire Date         0
dtype: int64

In [10]:
county_pr.columns.tolist()

['Fiscal Year',
 'Fiscal Quarter',
 'Fiscal Period',
 'First Name',
 'Last Name',
 'Middle Init',
 'Bureau',
 'Office',
 'Office Name',
 'Job Code',
 'Job Title',
 'Base Pay',
 'Position ID',
 'Employee Identifier',
 'Original Hire Date']

In [7]:
                                               #dropping column
county_pr = county_pr.drop(columns=['Middle Init'])

In [12]:
county_pr.head()

,Fiscal Year,Fiscal Quarter,Fiscal Period,First Name,Last Name,Bureau,Office,Office Name,Job Code,Job Title,Base Pay,Position ID,Employee Identifier,Original Hire Date
0,2016,1,2016Q1,AMRITH,AAKRE,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$20,088.00",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
1,2016,2,2016Q2,AMRITH,AAKRE,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$23,436.00",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
2,2016,3,2016Q3,AMRITH,AAKRE,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$20,422.82",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
3,2016,4,2016Q4,AMRITH,AAKRE,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$23,904.80",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005
4,2017,1,2017Q1,AMRITH,AAKRE,State's Attorney,1250.0,STATES ATTORNEY,1172,Assistant State's Attorney,"$20,745.80",9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,05/16/2005

In [8]:
county_pr[county_pr['Office'].isna() & county_pr['Office Name'].isna()].shape

(3184, 14)

In [9]:
county_pr['Base Pay'] = county_pr['Base Pay'].replace('[\$,]', '', regex=True).astype(float)
county_pr['Base Pay'].dtype

dtype('float64')

In [10]:
text_cols = [
    'Fiscal Period',
    'First Name',
    'Last Name',
    'Bureau',
    'Office',
    'Office Name',
    'Job Title',
    'Employee Identifier'
]

county_pr[text_cols] = county_pr[text_cols].astype('string')

In [11]:
county_pr['Job Code'] = county_pr['Job Code'].astype('string')
county_pr['Position ID'] = county_pr['Position ID'].astype('string')

In [12]:
county_pr['Original Hire Date'] = pd.to_datetime(
    county_pr['Original Hire Date'],
    errors='coerce'
)

In [13]:
county_pr.dtypes

Fiscal Year                     int64
Fiscal Quarter                  int64
Fiscal Period          string[python]
First Name             string[python]
Last Name              string[python]
Bureau                 string[python]
Office                 string[python]
Office Name            string[python]
Job Code               string[python]
Job Title              string[python]
Base Pay                      float64
Position ID            string[python]
Employee Identifier    string[python]
Original Hire Date     datetime64[ns]
dtype: object

In [14]:
county_pr['Office Name'].nunique()

160

In [15]:
county_pr['Job Title'].nunique()

2382

In [16]:
county_pr['Bureau'].nunique()

111

In [17]:
text_cols = ['First Name', 'Last Name', 'Office Name', 'Job Title', 'Bureau']
for col in text_cols:
 county_pr[col] = county_pr[col].str.strip().str.title()

In [18]:
county_pr['Office Name'].nunique()

134

In [19]:
county_pr['Job Title'].nunique()

2381

In [20]:
county_pr['Bureau'].nunique()

104

In [21]:
county_pr['Bureau'].unique()

<StringArray>
[              'State'S Attorney',                       'Assessor',
               'Bureau Of Health',      'Bureau Of Human Resources',
               'Bureau Of Admin.',              'Bureau Of Finance',
                    'Chief Judge',                        'Sheriff',
                      'Treasurer',     'Office Under The President',
 ...
        'Human Rights And Ethics',               'Seventh District',
 'Sheriff'S Information Technolo',     'Office County Commissioner',
            'Fourteenth District',              'Eleventh District',
                 'Third District',                 'Ninth District',
 'Board Of Elec Comm-Election Fu',     'Dept Of Environmental Ctrl']
Length: 104, dtype: string

In [22]:
county_pr[county_pr['Bureau'] == '.']

,Fiscal Year,Fiscal Quarter,Fiscal Period,First Name,Last Name,Bureau,Office,Office Name,Job Code,Job Title,Base Pay,Position ID,Employee Identifier,Original Hire Date
50140,2016,1,2016Q1,Brian,Flores,.,<NA>,<NA>,6053,Labor & Employment Counsel,14615.20,1000882,ed952885-28b0-4458-b23d-df755e249354,2015-12-28
50172,2016,2,2016Q2,Brian,Flores,.,<NA>,<NA>,6053,Labor & Employment Counsel,25211.22,1000882,ed952885-28b0-4458-b23d-df755e249354,2015-12-28
50204,2016,3,2016Q3,Brian,Flores,.,<NA>,<NA>,6053,Labor & Employment Counsel,21916.10,1000882,ed952885-28b0-4458-b23d-df755e249354,2015-12-28
50233,2016,4,2016Q4,Brian,Flores,.,<NA>,<NA>,6053,Labor & Employment Counsel,26089.00,1000882,ed952885-28b0-4458-b23d-df755e249354,2015-12-28
50263,2017,1,2017Q1,Brian,Flores,.,<NA>,<NA>,6053,Labor & Employment Counsel,22641.07,1000882,ed952885-28b0-4458-b23d-df755e249354,2015-12-28
50294,2017,2,2017Q2,Brian,Flores,.,<NA>,<NA>,6053,Labor & Employment Counsel,26479.81,1000882,ed952885-28b0-4458-b23d-df755e249354,2015-12-28
50325,2017,3,2017Q3,Brian,Flores,.,<NA>,<NA>,6053,Labor & Employment Counsel,11348.49,1000882,ed952885-28b0-4458-b23d-df755e249354,2015-12-28
145064,2016,1,2016Q1,Vanessa,Sarabia,.,<NA>,<NA>,5298,Security Specialist Ii,9871.20,9517387,780b57e6-0024-4a81-8548-a3f3ee3c8447,2013-03-11
145065,2016,2,2016Q2,Vanessa,Sarabia,.,<NA>,<NA>,5298,Security Specialist Ii,11913.20,9517387,780b57e6-0024-4a81-8548-a3f3ee3c8447,2013-03-11
145066,2016,3,2016Q3,Vanessa,Sarabia,.,<NA>,<NA>,5298,Security Specialist Ii,5173.73,9517387,780b57e6-0024-4a81-8548-a3f3ee3c8447,2013-03-11

In [23]:
county_pr['Bureau'] = county_pr['Bureau'].replace('.', 'Not Reported')

In [24]:
(county_pr['Bureau'] == 'Not Reported').sum()

np.int64(10)

In [25]:
county_pr.loc[
    county_pr['Office'].isna() & county_pr['Office Name'].isna(),
    'Employee Identifier'
].nunique()

842

In [26]:
missing_office_employees = county_pr.loc[
    county_pr['Office'].isna() & county_pr['Office Name'].isna(),
    'Employee Identifier'
].unique()

len(missing_office_employees)

842

In [27]:
employees_with_office = county_pr[
    county_pr['Employee Identifier'].isin(missing_office_employees) &
    county_pr['Office'].notna()
]['Employee Identifier'].nunique()

employees_with_office

823

In [28]:
office_status = county_pr.groupby('Employee Identifier')['Office'].agg(
    has_missing=lambda x: x.isna().any(),
    has_office=lambda x: x.notna().any()
)

employees_to_fill = office_status[
    office_status['has_missing'] & office_status['has_office']
].index
len(employees_to_fill)

823

In [34]:
county_pr[
    county_pr['Employee Identifier'].isin(employees_to_fill)
][[
    'Employee Identifier',
    'Fiscal Year',
    'Fiscal Quarter',
    'Fiscal Period',
    'Office',
    'Office Name'
]].sort_values(
    ['Employee Identifier', 'Fiscal Year', 'Fiscal Quarter']
).head(50)

,Employee Identifier,Fiscal Year,Fiscal Quarter,Fiscal Period,Office,Office Name
171113,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2016,1,2016Q1,1250.0,States Attorney
171118,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2016,2,2016Q2,1250.0,States Attorney
171123,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2016,3,2016Q3,1250.0,States Attorney
171129,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2016,4,2016Q4,1250.0,States Attorney
171134,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2016,4,2016Q4,1250.0,States Attorney
171139,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2017,1,2017Q1,1250.0,States Attorney
171144,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2017,2,2017Q2,1250.0,States Attorney
171149,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2017,3,2017Q3,1250.0,States Attorney
171154,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2017,4,2017Q4,<NA>,<NA>
206327,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2018,1,2018Q1,1250.0,States Attorney
231961,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2018,1,2018Q1,1250.0,States Attorney
203531,007ca4de-de2b-44ac-bf71-6eb4cbdc27e2,2018,2,2018Q2,1250.0,States Attorney
3503,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2016,1,2016Q1,<NA>,<NA>
3775,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2016,2,2016Q2,<NA>,<NA>
3776,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2016,3,2016Q3,<NA>,<NA>
3777,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2016,4,2016Q4,<NA>,<NA>
3778,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2017,1,2017Q1,<NA>,<NA>
3779,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2017,2,2017Q2,<NA>,<NA>
3780,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2017,3,2017Q3,<NA>,<NA>
3781,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2017,4,2017Q4,<NA>,<NA>
186397,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2018,1,2018Q1,<NA>,<NA>
196750,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2018,1,2018Q1,1779.0,Ccc Child Support Enforcement
216959,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2018,2,2018Q2,<NA>,<NA>
220044,008ed3c6-12bd-4a39-8ed4-7f79d4900dba,2018,2,2018Q2,1779.0,Ccc Child Support Enforcement
115494,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2016,1,2016Q1,1250.0,States Attorney
115495,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2016,2,2016Q2,1250.0,States Attorney
115496,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2016,3,2016Q3,1250.0,States Attorney
115497,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2016,4,2016Q4,1250.0,States Attorney
115498,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2017,1,2017Q1,1250.0,States Attorney
115499,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2017,2,2017Q2,1250.0,States Attorney
115500,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2017,3,2017Q3,1250.0,States Attorney
115501,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2017,4,2017Q4,1250.0,States Attorney
196514,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2018,1,2018Q1,1622.0,Sa Appellate Assistance Progra
198116,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2018,1,2018Q1,1250.0,Sa Appellate Assistance Progra
205293,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2018,1,2018Q1,<NA>,<NA>
195118,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2018,2,2018Q2,1622.0,Sa Appellate Assistance Progra
211169,00e833c8-ecbf-4e2c-9b66-9472d1949d79,2018,2,2018Q2,<NA>,<NA>
120348,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2016,1,2016Q1,4897.0,Stroger Hospital Of Cook Cnty
120356,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2016,2,2016Q2,4897.0,Stroger Hospital Of Cook Cnty
120363,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2016,3,2016Q3,4897.0,Stroger Hospital Of Cook Cnty
120370,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2016,4,2016Q4,4897.0,Stroger Hospital Of Cook Cnty
120371,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2016,4,2016Q4,4897.0,Stroger Hospital Of Cook Cnty
120379,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2017,1,2017Q1,4897.0,Stroger Hospital Of Cook Cnty
120387,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2017,2,2017Q2,4897.0,Stroger Hospital Of Cook Cnty
120394,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2017,3,2017Q3,4897.0,Stroger Hospital Of Cook Cnty
120402,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2017,4,2017Q4,4897.0,Stroger Hospital Of Cook Cnty
217673,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2018,1,2018Q1,<NA>,<NA>
230566,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2018,1,2018Q1,1897.0,Stroger Hospital Of Cook Cnty
194825,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2018,2,2018Q2,<NA>,<NA>
217964,01185f60-c7ea-4227-a8fb-7f40ccb8bdba,2018,2,2018Q2,1897.0,Stroger Hospital Of Cook Cnty

In [29]:
county_pr['Office'] = county_pr.groupby(
    'Employee Identifier'
)['Office'].transform(lambda x: x.ffill().bfill())

In [30]:
county_pr['Office Name'] = county_pr.groupby(
    'Employee Identifier'
)['Office Name'].transform(lambda x: x.ffill().bfill())

In [31]:
county_pr[county_pr['Office'].isna() & county_pr['Office Name'].isna()].shape

(67, 14)

In [32]:
county_pr.loc[
    county_pr['Office'].isna() & county_pr['Office Name'].isna(),
    'Employee Identifier'
].nunique()

19

In [33]:
county_pr['Office'] = county_pr['Office'].fillna('Not Reported')
county_pr['Office Name'] = county_pr['Office Name'].fillna('Not Reported')

In [34]:
county_pr[['Office', 'Office Name']].isna().sum()

Office         0
Office Name    0
dtype: int64

In [35]:
county_pr[county_pr['Base Pay'].isna()].shape

(4, 14)

In [36]:
county_pr = county_pr.dropna(subset=['Base Pay'])

In [37]:
county_pr['Base Pay'].isna().sum()

np.int64(0)

In [38]:
county_pr['Base Pay'].describe()

count    234295.000000
mean      16795.426916
std       10716.170305
min      -19562.150000
25%       11490.950000
50%       15826.420000
75%       20396.430000
max      242576.340000
Name: Base Pay, dtype: float64

In [39]:
negative_pay = county_pr[county_pr['Base Pay'] < 0]

negative_pay.shape

(22, 14)

In [40]:
(county_pr['Base Pay'] == 0).sum()

np.int64(2541)

In [41]:
zero_pay = county_pr[county_pr['Base Pay'] == 0]

zero_pay[
    ['Fiscal Year',
     'Fiscal Quarter',
     'Bureau',
     'Office',
     'Office Name',
     'Job Title',
     'Position ID',
     'Employee Identifier',
     'Original Hire Date']
].head(20)

,Fiscal Year,Fiscal Quarter,Bureau,Office,Office Name,Job Title,Position ID,Employee Identifier,Original Hire Date
66,2016,1,Bureau Of Admin.,1500.0,Dept. Of Transportation And Hw,Right Of Way Agent Ii,9517610,f52eb088-72d8-494a-a296-772a71783234,1986-06-20
68,2016,2,Chief Judge,1280.0,Adult Probation Dept.,Supervisor Adult Probation,9512676,e9a92ee0-120f-41f3-b824-4e4d7c43cc5c,1982-12-17
69,2016,3,Chief Judge,1280.0,Adult Probation Dept.,Supervisor Adult Probation,9512676,e9a92ee0-120f-41f3-b824-4e4d7c43cc5c,1982-12-17
72,2016,2,Bureau Of Health,4897.0,Stroger Hospital Of Cook Cnty,Medical Div Chairman Xii,800768,e07ba440-b785-4047-ab96-38c9714ce186,2009-08-17
92,2017,3,Sheriff,1239.0,Department Of Corrections,Correctional Officer,800096,433c0c09-b58e-45c0-96ee-1cf5c315cf5f,2011-06-27
242,2016,1,Bureau Of Health,4897.0,Stroger Hospital Of Cook Cnty,Ward Clerk,9523999,1c8cd36d-04ba-4e83-9769-52e3e4a8fd3a,1979-09-17
280,2016,1,Bureau Of Health,4897.0,Stroger Hospital Of Cook Cnty,Respiratory Therapist,9523160,c265d37e-7c11-458d-9d32-03111646b6cd,1992-10-05
562,2016,2,State'S Attorney,1250.0,States Attorney,Clerk V,9510764,bc26d7f7-2e1e-4bd5-be64-c2fda03b0a63,1989-02-16
563,2016,2,State'S Attorney,1250.0,States Attorney,Clerk V,9931957,36c468be-13f0-4037-a7fd-66099a9d5510,1991-08-16
592,2016,1,Sheriff,1239.0,Department Of Corrections,Correctional Officer,9507605,2c6b6b43-5e10-4a68-a94a-40b8ddba5fe7,1988-08-01
634,2017,1,Bureau Of Health,4897.0,Stroger Hospital Of Cook Cnty,Storekeeper/Supply Clerk,9521227,c0d52498-7026-4e7e-b563-fb718a35f4c6,1998-08-14
748,2017,3,Bureau Of Health,4897.0,Stroger Hospital Of Cook Cnty,Chair Of Div Of Post Grad Med,9521853,89210043-928e-43b2-ac5a-0dafd901b040,1993-07-01
765,2016,4,Sheriff,1239.0,Department Of Corrections,Correctional Lieutenant,9508451,3240b775-ab82-4999-b1d6-7ab9d98c8969,1999-06-21
867,2016,1,Bureau Of Health,4897.0,Stroger Hospital Of Cook Cnty,Sterile Processing Technician,903990,40215afc-3ca0-4d28-bfaa-e4bd0d98ac36,1993-08-30
887,2016,1,Clerk Of Circuit Ct.,1335.0,Clerk Of Crct Crt Off. Of Cler,Court Clerk/Trainer,9816552,5c80248b-dc3e-470f-b3a8-9848833bc682,1981-07-16
949,2016,4,Chief Judge,1440.0,Juvenile Temporary Detent.Cntr,Youth Dev Specialist Assoc I,9517123,4e737ab5-92db-438f-9534-1447a95ca218,2009-08-03
1409,2016,2,Bureau Of Health,4897.0,Stroger Hospital Of Cook Cnty,Attending Physician Sr Xii,9522611,aaf2b902-e08f-4786-ad78-ed99a9d2cf5e,2003-08-04
1418,2016,3,Public Defender,1260.0,Public Defender,Assistant Public Defender Iii,9511634,d4dd2ac2-d675-41c6-9554-37ed7d25947b,1993-08-16
1474,2016,4,Bureau Of Health,4240.0,Cermak Health Services,Licensed Practical Nurse Ii,9509523,140627c9-5977-4aed-b5fc-f3d8a8f824ce,1997-04-07
1570,2016,2,Chief Judge,1280.0,Adult Probation Dept.,Adult Probation Officer- Psb,9512448,523fd7b1-3d68-42f4-b2f9-7efb4cf0af75,1989-06-19

In [48]:
county_pr.head(5)

,Fiscal Year,Fiscal Quarter,Fiscal Period,First Name,Last Name,Bureau,Office,Office Name,Job Code,Job Title,Base Pay,Position ID,Employee Identifier,Original Hire Date
0,2016,1,2016Q1,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,20088.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16
1,2016,2,2016Q2,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,23436.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16
2,2016,3,2016Q3,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,20422.82,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16
3,2016,4,2016Q4,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,23904.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16
4,2017,1,2017Q1,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,20745.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16

In [42]:
county_pr['Negative Pay Flag'] = county_pr['Base Pay'] < 0

In [43]:
county_pr['Zero Pay Flag'] = county_pr['Base Pay'] == 0

In [51]:
county_pr.head(5)

,Fiscal Year,Fiscal Quarter,Fiscal Period,First Name,Last Name,Bureau,Office,Office Name,Job Code,Job Title,Base Pay,Position ID,Employee Identifier,Original Hire Date,Negative Pay Flag,Zero Pay Flag
0,2016,1,2016Q1,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,20088.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
1,2016,2,2016Q2,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,23436.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
2,2016,3,2016Q3,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,20422.82,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
3,2016,4,2016Q4,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,23904.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
4,2017,1,2017Q1,Amrith,Aakre,State'S Attorney,1250.0,States Attorney,1172,Assistant State'S Attorney,20745.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False

In [44]:
for i, bureau in enumerate(sorted(county_pr['Bureau'].dropna().unique()), 1):
    print(i, bureau)

1 Administrative Hearing Board
2 Adult Probation Dept.
3 Ambulatory Community Hlth Ntwk
4 Assessor
5 Board Of Elec Comm-Election Fu
6 Board Of Elections
7 Board Of Review
8 Boh Services Core Center
9 Budget & Management Services
10 Building & Zoning
11 Bureau Of Admin.
12 Bureau Of Economic Development
13 Bureau Of Finance
14 Bureau Of Health
15 Bureau Of Human Resources
16 Bureau Of Technology
17 Cermak Health Services
18 Chief Judge
19 Chief Procurement Officer
20 Clerk Of Circuit Ct.
21 Clerk Of Crct Crt Off. Of Cler
22 Cnty Brd Commissions
23 Contract Compliance
24 Corporate
25 County Assessor
26 County Auditor
27 County Clerk
28 County Comptroller
29 County Treasurer
30 Court Services Division
31 Department Of Corrections
32 Department Of Public Health
33 Dept Of Env Ctrl & Sustainblty
34 Dept Of Environmental Ctrl
35 Dept. Of Facilities/Mgmt
36 Dept. Of Human Resources
37 Dept. Of Transportation And Hw
38 Eighth District
39 Eleventh District
40 Emergency Management Agency
41 Enterprise Resource Planning
42 Facilities Management
43 Fifteenth District
44 Fifth District
45 First District
46 Forensic Clinical Services
47 Fourteenth District
48 Fourth District
49 Health
50 Human Rights And Ethics
51 Inspector General
52 Jtdc - Health Services
53 Judiciary
54 Justice Advisory Council
55 Juvenile Probation
56 Juvenile Temporary Detent.Cntr
57 Land Bank Authority
58 Managed Care
59 Medical Examiner
60 Ninth District
61 Not Reported
62 Oak Forest Health Center
63 Off Economic Dev
64 Off Of Prof Review  Integrity
65 Off Of The Chief Fncl Officer
66 Office Chief Admin Officer
67 Office County Commissioner
68 Office Inspector General
69 Office Of Asset Management
70 Office Of The Chief Judge
71 Office Of The President
72 Office Of The Sheriff
73 Office Under The President
74 Planning & Development
75 Police Department
76 Provident Hospital
77 Public Admin.
78 Public Administrator
79 Public Defender
80 Public Guardian
81 Recorder Of Deeds
82 Revenue
83 Risk Management
84 Second District
85 Seventeenth District
86 Seventh District
87 Sheriff
88 Sheriff'S Admin And Hr
89 Sheriff'S Information Technolo
90 Sheriff'S Merit Board
91 Sixteenth District
92 Sixth District
93 Social Casework Services
94 State'S Attorney
95 States Attorney
96 Stroger Hospital Of Cook Cnty
97 Supportive Services
98 Technology Policy And Planning
99 Tenth District
100 Third District
101 Thirteenth District
102 Treasurer
103 Twelfth District
104 Zoning Board Of Appeals

In [45]:
county_pr['Bureau'] = county_pr['Bureau'].replace({
    "State'S Attorney": "State's Attorney",
    "States Attorney": "State's Attorney"
})

In [46]:
county_pr[county_pr['Bureau'].str.lower().str.contains("state.*attorney", na=False)]['Bureau'].value_counts()

Bureau
State's Attorney    13526
Name: count, dtype: Int64

In [47]:
for i,  office_name in enumerate(sorted(county_pr['Office Name'].dropna().unique()), 1):
    print(i,office_name)

1 Administrative Hearing Board
2 Adult Probation Dept.
3 Ambulatory Community Hlth Ntwk
4 Ambulatory/Community Hlth Ntwk
5 Assisted Outpatient Treatment
6 Board Of Elec Comm-Election Fu
7 Board Of Review
8 Boh  Services Core Center
9 Boh Services Core Center
10 Budget & Management Services
11 Building & Zoning
12 Bureau Of Health
13 Cc Lead Poisoning Prevention
14 Cc Works Admin. Cost Pool
15 Ccc Child Support Enforcement
16 Cermak Health Services
17 Chief Procurement Officer
18 Cj Access And Visitation
19 Clerk Of Crct Crt Off. Of Cler
20 Clerk Of Crct Crt Off.Of Clerk
21 Comm Super./Intervention
22 Contract Compliance
23 County Assessor
24 County Auditor
25 County Clerk
26 County Clerk Election Div.Fund
27 County Comptroller
28 County Law Library
29 County Treasurer
30 Court Services Division
31 Department Of Corrections
32 Department Of Human Resources
33 Department Of Public Health
34 Dept Of Env Ctrl & Sustainblty
35 Dept Of Environmental Ctrl
36 Dept. Of Facilities/Mgmt
37 Dept. Of Human Resources
38 Dept. Of Transportation And Hw
39 Ec Air Pollution
40 Ec Illinois Science Foundation
41 Eighth District
42 Eleventh District
43 Emergency Management Agency
44 Emhs Homeland Security
45 Engineer To Order
46 Enterprise Resource Planning
47 Fifteenth District
48 Fifth District
49 First District
50 Forensic Clinical Services
51 Fourteenth District
52 Fourth District
53 Human Rights And Ethics
54 Intergovernmental Agrmnt/Etsb
55 It Solutions
56 Jac Family Justice Improvement
57 Jtdc - Health Services
58 Judiciary
59 Justice Advisory Council
60 Juvenile Probation
61 Juvenile Temporary Detent.Cntr
62 Land Bank Authority
63 Macarthur Internat'L Education
64 Macarthur Safety And Justice
65 Managed Care
66 Medicaid Expansion
67 Medical Examiner
68 Mft Illinois First (Ist)
69 Ninth District
70 Not Reported
71 Oak Forest Health Center
72 Off Economic Dev
73 Off Of Prof Review  Integrity
74 Off Of The Chief Fncl Officer
75 Office Chief Admin Officer
76 Office County Commissioner
77 Office Inspector General
78 Office Of Asset Management
79 Office Of Chief Admin. Officer
80 Office Of Economic Development
81 Office Of The Chief Judge
82 Office Of The President
83 Office Of The Sheriff
84 P&D Community Development
85 Pd Mitigator Project
86 Ph Bioterrorism Preparedness
87 Ph Breast And Cervical Cancer
88 Ph Health Inspections Intergov
89 Ph Idph Health Services
90 Ph Il Dept Of Human Services
91 Ph Il Tobacco-Free Communities
92 Ph Supplemental Nutrition Wic
93 Planning & Development
94 Police Department
95 Professional Investigators
96 Provident Hospital
97 Public Administrator
98 Public Defender
99 Public Guardian
100 Recorder Of Deeds
101 Revenue
102 Risk Management
103 Sa Appellate Assistance Progra
104 Sa Child Support Enforcement
105 Sa Community Justice Center
106 Sa Complex Drug Prosecutions
107 Sa Human Trafficking Equipment
108 Sa Mayer Brown Civil Program
109 Sa Sexual Assault Division
110 Sa Victim Sensitive Interview
111 Second District
112 Seventeenth District
113 Seventh District
114 Sh Idhs Wic
115 She Child Support Enforcement
116 Sheriff Admin & Hr
117 Sheriff Information Technology
118 Sheriff'S Admin And Hr
119 Sheriff'S Information Technolo
120 Sheriff'S Merit Board
121 Sixteenth District
122 Sixth District
123 Social Casework Services
124 State'S Attorney
125 States Attorney
126 Stroger Hospital Of Cook Cnty
127 Supportive Services
128 Technology Policy And Planning
129 Tenth District
130 Third District
131 Thirteenth District
132 Treasurer Tax Sales Automation
133 Twelfth District
134 Wrap Drug Courts
135 Zoning Board Of Appeals

In [48]:
county_pr['Office Name'] = county_pr['Office Name'].replace({
    'Ambulatory Community Hlth Ntwk': 'Ambulatory/Community Hlth Ntwk',
    'Boh  Services Core Center': 'Boh Services Core Center',
    'Clerk Of Crct Crt Off.Of Clerk': 'Clerk Of Crct Crt Off. Of Cler',
    'Department Of Human Resources': 'Dept. Of Human Resources',
    'Off Economic Dev': 'Office Of Economic Development',
    'Office Chief Admin Officer': 'Office Of Chief Admin. Officer',
    'Sheriff Admin & Hr': "Sheriff'S Admin And Hr",
    'Sheriff Information Technology': "Sheriff'S Information Technolo",
    "State'S Attorney": "State's Attorney",
    'States Attorney': "State's Attorney"
})

In [49]:
county_pr['Office Name'].nunique()

126

In [50]:
county_pr['Job Title'] = (
    county_pr['Job Title']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
    .str.title()
)

In [51]:
for i,  job_title in enumerate(sorted(county_pr['Job Title'].dropna().unique()), 1):
    print(i,job_title)

1 340B Program Analyst
2 340B Program Manager
3 Academic Leader In Med Educ
4 Accountant I
5 Accountant I Senior Ccc
6 Accountant Ii
7 Accountant Ii Senior Ccc
8 Accountant Iii
9 Accountant Iii-Ccc
10 Accountant Iv
11 Accountant Iv-Ccc
12 Accountant V
13 Accountant V-Ccc
14 Accountant Vii-Ccc
15 Accountant Viii-Ccc
16 Accounting Analyst
17 Accounting Systems Analyst
18 Accounts Payable Clerk
19 Accounts Payable Coordinator
20 Accounts Payable Specialist Ii
21 Accts Payable Specialist Iii
22 Acquisitions Specialist
23 Activities Therapist Ii
24 Acupuncturist
25 Ada Compliance Project Direct
26 Adlt Probat Depchief Intensive
27 Adm Asst To Comm Ii Bd Of Apps
28 Adm Asst To State'S Attorney
29 Admin Analyst Iii-Sheriff
30 Admin Analyst Iv-Sheriff
31 Admin Analyst V-Sheriff
32 Admin Assistant I
33 Admin Assistant I (Seiu 73)
34 Admin Assistant I Senior Ccc
35 Admin Assistant I-Cnty Clk/Shf
36 Admin Assistant I-County Clerk
37 Admin Assistant Ii
38 Admin Assistant Ii-Cc/Rod/Shf
39 Admin Assistant Ii-County Clk
40 Admin Assistant To Secretary
41 Admin Asst To Comm Brd Of Appl
42 Admin Asst To County Clerk I
43 Admin Asst To County Clerk Ii
44 Admin Supp For Police Records
45 Admin Support For Payroll
46 Admin Support I-County Clerk
47 Admin Support Viii-Ccc
48 Administrative Aide
49 Administrative Aide Ccu
50 Administrative Aide I Ccc
51 Administrative Aide Ii Ccc
52 Administrative Aide/Tmstr
53 Administrative Analyst I
54 Administrative Analyst Ii
55 Administrative Analyst Iii
56 Administrative Analyst Iv
57 Administrative Analyst V
58 Administrative Assistant I
59 Administrative Assistant Iii
60 Administrative Assistant Iv
61 Administrative Assistant V
62 Administrative Asst V-Cchhs
63 Administrative Coord/Sheriff
64 Administrative Coordinator
65 Administrative Coordinator Iii
66 Administrative Director
67 Administrative Hearings Clerk
68 Administrative Supervisor Ii
69 Administrative Support Ii
70 Administrative Support Ii-Ccc
71 Administrative Support Iii
72 Administrative Support Iii-Ccc
73 Administrative Support Iv
74 Administrative Support Iv-Ccc
75 Administrative Support V
76 Administrative Support V-Ccc
77 Administrative Support Vi
78 Administrative Support Vi-Ccc
79 Administrative Support Vii
80 Administrative Suppt For Foia
81 Administrator Of Programs
82 Administratrative Support Viii
83 Adopt And Child Custody Fam Sp
84 Adult Probat Depchief Pretrial
85 Adult Probation Deputy Chief
86 Adult Probation Intensive
87 Adult Probation Officer
88 Adult Probation Officer I- Psb
89 Adult Probation Officer- Psb
90 Adult Probation Officer- Psc
91 Adult Probation Weapons Supv
92 Advan Prac Prvdr Credent Spec
93 Aide To The Chief Of Staff
94 Aide To The Commissioner I
95 Aide To The Commissioner Ii
96 Aide To The Dep Chf Of Staff
97 Aide To The President
98 Ambulatory Clinic Manager
99 Anesthesia Technician
100 Animal Contrl Field Supervisor
101 Animal Control Admin Director
102 Animal Control Field Superviso
103 Animal Control Warden
104 Animal Technician
105 Apn-Cert Reg Nurse Anesthetist
106 Apn-Cert Regist Nurse Midwife
107 Apn-Clinical Nurse Specialist
108 Apn-Crna Chief Nurse Anesthet
109 Apn-Nurse Practitioner
110 Appeals Analyst I
111 Appeals Analyst Ii
112 Appeals Analyst Iii
113 Application Developer
114 Application Developer-Seiu
115 Application Support Analyst
116 Arch Iron Worker Foreman
117 Architect Ii
118 Architectural Iron Worker
119 Assessment Analyst Iii
120 Assessment Analyst Iv
121 Asset Manager
122 Assistant Administrator
123 Assistant Chief Deputy Clerk I
124 Assistant Chief Deputy Clk Ii
125 Assistant Chief Deputy Clk Iii
126 Assistant Chief Plan Examiner
127 Assistant Claims Adjuster
128 Assistant Comptroller-Ccc
129 Assistant Director
130 Assistant Director Pretrial
131 Assistant Executive Director
132 Assistant General Counsel
133 Assistant General Counsel I
134 Assistant General Counsel Ii
135 Assistant General Counsel Iii
136 Assistant General Counsel Iv
137 Assistant General Counsel V
138 Assistant Manager Iii-Ccc
139 Assistant Manager Iv-Ccc
140 Assistant Manager V Ccc
141 Assistant Payroll Supervisor
142 Assistant Procurement Officer
143 Assistant Program Coordinator
144 Assistant Public Defender I
145 Assistant Public Defender Ii
146 Assistant Public Defender Iii
147 Assistant Public Defender Iv
148 Assistant Public Guardian
149 Assistant State'S Attorney
150 Assistant Superintendent
151 Assistant Team Leader Jtdc
152 Assistant To Commissioner
153 Assistant To County Clerk
154 Assistant To County Recorder
155 Assistant To Director
156 Assistant To Judge Iv
157 Assited Outpt Treatmt Case Mgr
158 Assited Outpt Treatmt Proj Mgr
159 Assoc Adm Matl Svcs Cch
160 Assoc Chair Div Of Pain Mgmt
161 Assoc Dir Correctional Psychia
162 Assoc Dir Of Info Technology
163 Assoc Dir Of Internal Audit
164 Assoc Med Dir Amb Pediatrics
165 Assoc Med Dir Of Prim Cr Achn
166 Assoc Medical Director Sc
167 Assoc Nrs Ex Qual Dev Adv Prac
168 Assoc Nurse Exec Amb Srvc
169 Assoc Nurse Exec Hsptl Bsd Sr
170 Assoc Nurse Exec Inpatient
171 Assoc Nurse Exec Outpatient
172 Associate Admin Nursing Servic
173 Associate Administrator
174 Associate Clerk Circuit Court
175 Associate Director Of Nursing
176 Associate General Counsel
177 Associate Judge Circuit Court
178 Associate Medical Director
179 Associated Medical Chairman
180 Asst Chief Adult Probation
181 Asst Chief Deputy Sheriff
182 Asst Claims Mgr Workers Cmp
183 Asst Deputy Bureau Chief
184 Asst Dir Chicago Hidta Office
185 Asst Dir Environmental Service
186 Asst Dir Nursing And Patient
187 Asst Dir Occupational Therapy
188 Asst Dir Of Court Casework
189 Asst Dir Of Pharmacy
190 Asst Dir Of Quality Assurance
191 Asst Dir,Chicago Hidta Office
192 Asst Director Physical Therapy
193 Asst Div Nursing Director
194 Asst General Counsel Chhs
195 Asst Grants Mgmt Director
196 Asst Highway Superintendent
197 Asst Manager Freedom Of Info
198 Asst Manager Ic Valuations
199 Asst Manager Records Managment
200 Asst Manager Resident Model
201 Asst Manager Taxpayer Infor
202 Asst Mangr Of Exemption Proces
203 Asst Medical Examiner I E1
204 Asst Medical Examiner I E6
205 Asst Medical Examiner Ii E13
206 Asst Medical Examiner Ii E8
207 Asst Medical Examiner Ii E9
208 Asst Mgr Diagnostic Radiology
209 Asst Mgr I- Court Operations
210 Asst Mgr Of Resident Process
211 Asst Mgr Of Technical Review
212 Asst Prog Coord-Emerg Prep/Ph
213 Asst Public Defender Superv
214 Asst Public Defender Superviso
215 Asst Special Legal Counsel
216 Asst To Chief Admin Services
217 Asst To Chief Of Adm Svc Ii
218 Att Phys-Correctional Psych
219 Att Physician Dermatology
220 Att Physician Sr Vi Non-Union
221 Att Physician Sr Vii Non Union
222 Att Physician Sr X - Non Union
223 Att Physician Sr. Xi Non Union
224 Att Physician Vii - Non-Union
225 Att Physician Viii Non Union
226 Attend Physician Sr Ix Sc
227 Attend Physician Sr Vii-Sc
228 Attend Physician Sr Viii-Sc
229 Attend Physician Sr Xii Sc
230 Attend Physician Xii-Sc-Union
231 Attendant Patient Care
232 Attendant Patient Care As Req
233 Attendant Patient Care Cch
234 Attending Physician Iv
235 Attending Physician Iv-Sc
236 Attending Physician Ix
237 Attending Physician Ix-Sc
238 Attending Physician Senior 6
239 Attending Physician Senior V
240 Attending Physician Senior Vii
241 Attending Physician Sr Ix
242 Attending Physician Sr V-Sc
243 Attending Physician Sr Vi-Sc
244 Attending Physician Sr Viii
245 Attending Physician Sr X
246 Attending Physician Sr X-Sc
247 Attending Physician Sr Xi
248 Attending Physician Sr Xi Sc
249 Attending Physician Sr Xii
250 Attending Physician V
251 Attending Physician V-Sc
252 Attending Physician Vi
253 Attending Physician Vi-Sc
254 Attending Physician Vii
255 Attending Physician Vii-Sc
256 Attending Physician Viii
257 Attending Physician Viii-Sc
258 Attending Physician X
259 Attending Physician X-Sc
260 Attending Physician Xi
261 Attending Physician Xi-Sc
262 Attending Physician Xii
263 Attending Physician Xii-Sc
264 Attending Physician Xii-Sc-Non
265 Attorney - Public Guardian
266 Attorney Adult Redeploy Il
267 Attorney-Jtdc
268 Audiologist Ii
269 Audit Coordinator-Sheriff
270 Auditing Supervisor
271 Autopsy Technician Ii
272 Autopsy Technician Supervisor
273 Barber
274 Barber Instructor
275 Barber Supervisor
276 Behav Hlth Triage Soc Wrker
277 Behavior Hlth Integration Mgr
278 Behavioral Health Program Mgr
279 Benefits Administrator
280 Benefits And Wellness Coord
281 Benefits Assistant
282 Benefits Coordinator
283 Benefits Coordinator-Sheriff
284 Benefits Representative
285 Bilngl Patient Care Navigator
286 Bindery Digital Printer Opr
287 Bio-Medical Engineer
288 Bio-Medical Technician
289 Biochemist Ii
290 Biochemist Iii
291 Biomedical Electrical Tech
292 Bldng Srvc Wrkr Seiu 73)
293 Blood Laboratory Supervisor
294 Boiler Washer
295 Boilermaker-Welder
296 Bookkeeper Ii Senior Ccc
297 Bookkeeper Iii
298 Bookkeeper Iv
299 Bookkeeper Iv-County Clerk
300 Bookkeeper Ix-Ccc
301 Bookkeeper Vi
302 Bookkeeper Vii-Ccc
303 Bookkeeper Viii-Ccc
304 Bookkeeper X-Ccc
305 Bricklayer
306 Bricklayer Foreman
307 Budget & Mgmt Servics Director
308 Budget Analyst Ii
309 Budget Analyst Iii
310 Budget Analyst V
311 Budget Analyst V/State'S Attor
312 Building And Zoning Architect
313 Building And Zoning Inspector
314 Building Code Administrator
315 Building Custodian I
316 Building Custodian Ii
317 Building Service Leader
318 Building Service Supervisor
319 Building Service Worker
320 Building Service Worker- Cch
321 Building Service Worker- Prov
322 Buildingsrvcworker(Seiu73)Ofc
323 Bureau Chief
324 Business Analyst
325 Business Analyst-Seiu
326 Business Manager 1 - Cchhs
327 Business Manager I
328 Business Manager Ii
329 Business Manager Ii-Hhs Union
330 Business Manager Iii
331 Business Manager Iv
332 Business Manager V
333 Business Office Supervisor
334 Buyer Iv
335 Cabs Id System Analyst
336 Cabs Id System Analyst/Sheriff
337 Cadd Operator I
338 Cadd Operator Ii
339 Cadd Operator Ii/T&H
340 Call Center Cust Sevice Rep
341 Call Center Manager
342 Call Center Operations Analyst
343 Call Center Supervisor
344 Call Center Trainer
345 Call Ctr Document Processor
346 Cancer Genetic Counselor
347 Cancer Registrar
348 Cancer Registrar Trainee
349 Canine Specialist
350 Capital Assets Manager
351 Capital Buyer
352 Cardiology Fellow Program Dir
353 Care Coordinator-Brain Injury
354 Care Coordinator-Disability
355 Care Coordinator-Elderly
356 Care Coordinator-Hiv/Aids
357 Carpenter
358 Carpenter Foreman
359 Case Management Supervisor/Pg
360 Case Manager-Sheriff
361 Casework Supervisor/Pub Guard
362 Caseworker Ii Jtdc
363 Caseworker Ii Public Grdian
364 Caseworker Iii
365 Caseworker Iii - Cchhs
366 Caseworker Iii Public Grdian
367 Caseworker Iv
368 Caseworker Jtdc
369 Caseworker Mang Unit
370 Caseworker V
371 Caseworker-Oak Forest Hospital
372 Cash Applicat Representative
373 Cash Management Director
374 Cashier Div Supervisor Ii
375 Cashier Division Supervisor I
376 Cashier I Recorder
377 Cashier Ii
378 Cashier Ii Recorder
379 Cashier Ii Senior Ccc
380 Cashier Ii-Rod
381 Cashier Iii
382 Cashier Iii Recorder
383 Cashier Iv-Ccc
384 Cashier Revenue
385 Cashier V Recorder Of Deeds
386 Cashier V-Ccc
387 Cat Technologist
388 Cataloguer I
389 Cataloguer I (Seiu 73)
390 Cchhs Compliance Officer
391 Cchhs Employment Plan Officer
392 Ccoms And Foia Data Analyst
393 Central Dispatch Operator
394 Central Payment Distributor
395 Central Payroll Proc Asst
396 Central Payroll Processor I
397 Central Payroll Processor Ii
398 Central Payroll Processor Iii
399 Central Sterile Supply Coord
400 Cermak Med Asst Trtmt Nurse
401 Certification Compliance Off
402 Certified Ccl Programmer-Chs
403 Certified Hand Therapist
404 Certified Interpreter
405 Certified Nursing Assistant
406 Certified Nursing Asst Arnte
407 Cfo Bureau Of Health Svcs
408 Ch Dpt Of Cor Hlth Md Dir Cmk
409 Ch Of The Dept Of Pathology
410 Ch Of The Dept Of Psychiatry
411 Ch Of The Div Of Ad Cardil Cl
412 Ch Of The Div Of Ad Em Med Sv
413 Ch Of The Div Of Ad Outpt Psyc
414 Ch Of The Div Of Cons Liasion
415 Ch Of The Div Of Emerg Med Ed
416 Ch Of The Div Of Family Plan
417 Ch Of The Div Of Gen Ob Gyne
418 Ch Of The Div Of Hosp Med
419 Ch Of The Div Of Mammography
420 Ch Of The Div Of Mat Fet Med
421 Ch Of The Div Of Medicine Adm
422 Ch Of The Div Of Micro Viro
423 Ch Of The Div Of Musculos Imag
424 Ch Of The Div Of Neonatology
425 Ch Of The Div Of Neuro Anesth
426 Ch Of The Div Of Nuclear Med
427 Ch Of The Div Of Obs And Qual
428 Ch Of The Div Of Ot Pt Im Ctr
429 Ch Of The Div Of Pain Mgmt
430 Ch Of The Div Of Pre Hosp Med
431 Ch Of The Div Of Psychiatry Er
432 Ch Of The Div Of Pul Med Icu
433 Ch Of The Div Of Radiology Adm
434 Ch Of The Div Of Ren Dis Nep
435 Ch Of The Div Of Research
436 Ch Of The Div Of Toxicology
437 Ch Of The Div Of Tr Res Educ
438 Ch Of The Div Of Trauma Admin
439 Ch Of The Div Of Trauma Int Cr
440 Ch Of The Div Of Ultra Sound
441 Ch Of The Dpt Of Fam & Com Med
442 Ch Of The Dv Of Pr Hl Cr V Pr
443 Chair Dept Of Trauma Burn Svc
444 Chair Of Div Of Cardioth Surg
445 Chair Of Div Of Post Grad Med
446 Chair Of The Dept Of Medicine
447 Chair Of The Dept Of Oral Hlth
448 Chair Of The Div Of Gen Med
449 Chair Of The Div Of Pediatrics
450 Chair Of The Div Of Sur Cr Car
451 Chair Section Palliative Care
452 Chairman
453 Chairman Of Finance
454 Chairman-Sheriff'S Merit Bd
455 Charge Entry Representative
456 Chemist Ii
457 Chf Corp Compl And Privacy Off
458 Chf Oper Off-Hosp Based Srvcs
459 Chf Operating Off Ambul Svcs
460 Chief Accountant-Cchhs
461 Chief Administrative Officer
462 Chief Adult Probation Officer
463 Chief Building Inspector
464 Chief Civil Division-Sheriff
465 Chief Clerk Board Of Appeals
466 Chief Commercial Hearings Off
467 Chief Corp Comp & Priv Ofcr
468 Chief Correctional Psych
469 Chief Court Reporter
470 Chief Data Officer
471 Chief Day Reporting
472 Chief Deputy Assessor-Assessor
473 Chief Deputy Clerk Admin
474 Chief Deputy Clerk I
475 Chief Deputy Clerk Iii
476 Chief Deputy Clerk Iv
477 Chief Deputy Commissioner
478 Chief Deputy Director
479 Chief Deputy Recorder
480 Chief Deputy Sheriff
481 Chief Electrical Inspector
482 Chief Executive Officer
483 Chief Executive Officer -Cchhs
484 Chief Fin'L Ofcr-Cchhs
485 Chief Financial Officer
486 Chief General Counsel
487 Chief Hr Officer-Ccc
488 Chief Human Resources Officer
489 Chief Info Ofcr-Cchhs
490 Chief Information Officer
491 Chief Information Security Off
492 Chief Inspector
493 Chief Invest Bureau St Attny
494 Chief Investigator-Assessor
495 Chief Lgl Advsr-Recorder
496 Chief Med Info Officer
497 Chief Medical Examiner
498 Chief Medical Info Officer
499 Chief Medical Officer
500 Chief Nursing Officer
501 Chief Nursing Officer-Cchhs
502 Chief Of Admin Services
503 Chief Of Courts-Sheriff
504 Chief Of Executive Protection
505 Chief Of Fugitive Unit-Sheriff
506 Chief Of Human Resources
507 Chief Of Human Resources - Rod
508 Chief Of Logistics-Dhsem
509 Chief Of Planning-Dhsem
510 Chief Of Staff
511 Chief Of Staff-Doc
512 Chief Of Staff-Sheriff
513 Chief Of Staff/Exec Clk Pp&Hr
514 Chief Operating Officer
515 Chief Performance Officer
516 Chief Plan Examiner
517 Chief Plumbing Inspector
518 Chief Probation Officer
519 Chief Procurement Officer
520 Chief Quality Officer
521 Chief Radiology Technician
522 Chief Resident
523 Chief Security Officer
524 Chief Technology Officer
525 Chief Telecommunications Elect
526 Child Death Investigator
527 Child Supp&Civil Warrants Mgr
528 Chr Of The Div Of Colon Rectal
529 Chr Of The Div Of Cor Health
530 Chr Of The Div Of Neuro Surg
531 Chr Of The Div Of Opht Surg
532 Chr Of The Div Of Ortho Surg
533 Chr Of The Div Of Otol Surg
534 Chr Of The Div Of Pediat Surg
535 Chr Of The Div Of Plast Surg
536 Chr Of The Div Of Pod Surgery
537 Chr Of The Div Of Urology Surg
538 Civil Writ Supervisor
539 Cl Lab Automated Svs Supv
540 Cl Lab Microbiology Svc Sup I
541 Cl Lab Poct Pre&Post-Ansvcs Mg
542 Cl Lab Poct,Pre&Post-Ansvcs Mg
543 Cl Lab Pre-Anly Sv Phleb Sup I
544 Cl Lab Sys Quality Manager
545 Cl Lab Transfusion Svcs Supv I
546 Cl Lab Transfusion Svcs Sy Mgr
547 Cl Lab Virol Molecular Sv Sp I
548 Claims Adjuster Ii
549 Claims Manager General Liab
550 Claims Mgr Worker Compensation
551 Class & Comp Manager-Cchhs
552 Class & Compensation Analyst
553 Classification Specialist-Sher
554 Clerk Iv
555 Clerk Iv (Seiu73)
556 Clerk Iv Afscme
557 Clerk Iv Chief Judge Afscme
558 Clerk Iv Public Health
559 Clerk Iv Public Health Afscme
560 Clerk Iv Senior Courts
561 Clerk Iv, Senior Courts
562 Clerk Iv- County Clerk/Sheriff
563 Clerk Iv-Chief Judge
564 Clerk Iv-Clk/Rod/Sherif Seiu73
565 Clerk Iv-Cnty Clk/Rod/Sheriff
566 Clerk Iv-Recorder Of Deeds
567 Clerk Of The Circuit Court
568 Clerk Typist
569 Clerk Typist Afscme
570 Clerk Typist Senior
571 Clerk Typist Senior Afscme
572 Clerk V
573 Clerk V (Seiu73)
574 Clerk V-Clk/Rod/Sheriff-Seiu73
575 Clerk V-Cnty Clk/Rod/Sheriff
576 Clerk V-County Clerk
577 Clerk V-County Clerk/Sheriff
578 Clin Perform Improv Analyst
579 Clinic Coordinator
580 Clinical Case Manager
581 Clinical Documentation Special
582 Clinical Lab Auto Svcs Sys Mgr
583 Clinical Lab Site Superv Ii
584 Clinical Lab Site Supervisor I
585 Clinical Laboratory Supv Ii
586 Clinical Laboratory Supv Iii
587 Clinical Nurse I
588 Clinical Nurse Ii
589 Clinical Psychologist Iii
590 Clinical Specialist
591 Cln Decis Supt Alst Pcmh Os
592 Closing Specialist
593 Cluster Med Dir Of Hiv Service
594 Cmmc Economic Develop Prg Mgr
595 Coder-Physician Based
596 Coder-System Based
597 Collections Analyst
598 Collector
599 Collector Afscme
600 Colorectal Surg Fel Prog Dir
601 Comm And Soc Srvs Mgr-Cty Care
602 Comm Based Nurse Care Coord
603 Comm Dev Project Manager
604 Commissary Coordinator
605 Commissioner
606 Commissioner/Board Of Review
607 Commissioners Staff
608 Communications Manager
609 Communications Spec/Spokespers
610 Community Engagement Coordinat
611 Community Health Worker
612 Community Outreach Rep I
613 Community Outreach Rep Ii
614 Community Outreach Worker
615 Community Services Coord
616 Communitybasedsocworkcarecoord
617 Compensation Analyst
618 Compliance Analyst
619 Compliance Analyst-Revenue
620 Compliance Officer
621 Compliance Officer - Cchhs
622 Compliance Officer-Sheriff
623 Compliance Prog Specialist
624 Comptroller
625 Computer Oper I Sr Courts
626 Computer Oper I, Sr Courts
627 Computer Oper Ii Sr Courts
628 Computer Oper Ii, Sr Courts
629 Computer Operator I
630 Computer Operator Ii
631 Computer Operator Iii
632 Computer Operator Iv
633 Computer Operator Iv-Ccc
634 Computer Operator V
635 Computer Technician Iii
636 Conciliation Counselor
637 Condominium Valuation Grp Ldr
638 Const Mgr Correctio Facilities
639 Construction Manager/Jtdc
640 Consultant Physician
641 Contract Administrator
642 Contract Compliance Officer
643 Contract Negotiator
644 Coo Ambulatory Srvc
645 Coo Hsptl Based Srvc
646 Coo Integrated Care Srvc
647 Coo, Hsptl Based Srvc
648 Coo, Integrated Care Srvc
649 Coo-Corrct'L Health Services
650 Cook
651 Cook (Seiu 73)
652 Cook Ii
653 Cook Ii Sheriff
654 Coord Of Video Transfer Spec
655 Coordinator Of Safety
656 Correctional Chf Of Dental Svc
657 Correctional Commander
658 Correctional Lieutenant
659 Correctional Medical Tech Ii
660 Correctional Medical Tech Iii
661 Correctional Medical Tech Iv
662 Correctional Medical Tech V
663 Correctional Officer
664 Correctional Psychologist
665 Correctional Sergeant
666 Corrections Visitor Info Mgr
667 Corrections Visitor Info Spec
668 Cosmetologist
669 Cost Accountant
670 Cost Analyst Ii
671 Counselor Iii
672 County Assessor
673 County Auditor
674 County Clerk
675 County Commissioner
676 County Police Lieutenant
677 County Police Officer
678 County Police Sergeant
679 County Treasurer
680 Court Clerk I
681 Court Clerk Ii
682 Court Clerk Iii
683 Court Clerk/Trainer
684 Court Coodinator Iii
685 Court Coordinator I
686 Court Coordinator Ii
687 Court Coordinator Iv
688 Court Coordinator V
689 Court Interpreter

In [52]:
job_title_map = {
    'State\'S Attorney': 'State\'s Attorney',
    'States Attorney': 'State\'s Attorney',
    'Ambulatory Community Hlth Ntwk': 'Ambulatory/Community Health Network',
    'Ambulatory/Community Hlth Ntwk': 'Ambulatory/Community Health Network',
    'Boh  Services Core Center': 'BOH Services Core Center',
    'Boh Services Core Center': 'BOH Services Core Center',
    'Clerk Of Crct Crt Off. Of Cler': 'Clerk Of Circuit Court Office Of Clerk',
    'Clerk Of Crct Crt Off.Of Clerk': 'Clerk Of Circuit Court Office Of Clerk',
    'Warehouse Records Clerk I  Sr': 'Warehouse Records Clerk I, Sr',
    'Warehouse Records Clerk I, Sr': 'Warehouse Records Clerk I, Sr',
}

county_pr['Job Title'] = county_pr['Job Title'].replace(job_title_map)

In [53]:
county_pr['Job Title'].nunique()

2381

In [54]:
from difflib import get_close_matches

titles = county_pr['Job Title'].dropna().unique()

for title in titles:
    matches = get_close_matches(title, titles, n=3, cutoff=0.85)
    if len(matches) > 1:
        print(title, '->', matches[1:])

Attending Physician Xii -> ['Attending Physician Xi', 'Attending Physician Vii']
Chief Of Human Resources -> ['Dep Chief Of Human Resources', 'Chief Of Human Resources - Rod']
Clinical Nurse Ii -> ['Clinical Nurse I']
Pat Access Supervisor Fin Coun -> ['Pat Access Supervisor,Fin Coun']
Motor Vehicle Driver- Rr -> ['Motor Vehicle Driver I', 'Motor Vehicle Driver Ii']
Attending Physician Xi -> ['Attending Physician Xii', 'Attending Physician X']
Medical Div Chairman Xii -> ['Medical Div Chairman Xi', 'Medical Div Chairman X']
Administrative Assistant Iii -> ['Administrative Assistant I', 'Administrative Assistant Iv']
Administrative Assistant Iv -> ['Administrative Assistant I', 'Administrative Assistant Iii']
Clinical Nurse I -> ['Clinical Nurse Ii']
Medical Technologist I -> ['Medical Technologist Ii', 'Medical Technologist Iii']
Administrative Assistant V -> ['Administrative Assistant I', 'Administrative Assistant Iv']
Resident Field Inspector Ii -> ['Residential Field Inspector I', 'Residential Field Inspect Iii']
Attending Physician Sr Viii -> ['Attending Physician Sr Xii', 'Attending Physician Viii']
Attend Physician Sr Viii-Sc -> ['Attend Physician Sr Vii-Sc', 'Attending Physician Sr Vi-Sc']
Probation Officer Ii- Psb -> ['Probation Officer Ii-Psby', 'Probation Officer Ii-Y']
Adult Probation Officer- Psc -> ['Adult Probation Officer- Psb', 'Adult Probation Officer I- Psb']
Attending Physician Vii -> ['Attending Physician Viii', 'Attending Physician Vi']
Senior Project Manager -> ['Senior Project Eng', 'Hr Project Manager']
Security Specialist I-Jtdc -> ['Security Specialist Ii']
Attending Physician Ix -> ['Attending Physician Iv', 'Attending Physician Sr Ix']
Medical Technologist Iii -> ['Medical Technologist Ii', 'Medical Technologist I']
Food Service Worker -> ['Food Service Worker I']
Attending Physician Ix-Sc -> ['Attending Physician Iv-Sc', 'Attending Physician X-Sc']
Sanitarian I -> ['Sanitarian Iv', 'Sanitarian Ii']
Food Service Worker (Seiu 73) -> ['Food Service Wrkr(Seiu 73)Ofhc']
Admin Assistant I-Cnty Clk/Shf -> ['Admin Assistant Ii-County Clk', 'Admin Assistant I-County Clerk']
Investigator I -> ['Investigator Iv', 'Investigator Ii']
Investigator Ii -> ['Investigator Iii', 'Investigator I']
Chief Financial Officer -> ['Deputy Chief Financial Officer']
Court Clerk I -> ['Court Clerk Ii', 'Court Clerk Iii']
Chief Deputy Clerk Iii -> ['Chief Deputy Clerk I', 'Chief Deputy Clerk Iv']
Youth Development Specialist -> ['Prof Development Specialist']
Building Service Worker- Cch -> ['Building Service Worker', 'Building Service Worker- Prov']
Deputy Sheriff Ii -> ['Deputy Sheriff D2B']
Administrative Support Vii -> ['Administrative Support Vi', 'Administrative Support Iii']
Clerk V-County Clerk/Sheriff -> ['Clerk Iv- County Clerk/Sheriff', 'Clerk V-Cnty Clk/Rod/Sheriff']
Budget Analyst Iii -> ['Budget Analyst Ii', 'Budget Analyst V']
Investigator Iv -> ['Investigator I', 'Investigator Ii']
Investigator Iii -> ['Investigator Ii', 'Investigator I']
Court Coordinator I -> ['Court Coordinator Iv', 'Court Coordinator Ii']
Adult Probation Officer I- Psb -> ['Adult Probation Officer- Psb', 'Adult Probation Officer- Psc']
Court Clerk Ii -> ['Court Clerk Iii', 'Court Clerk I']
Probation Officer I -> ['Probation Officer Ii', 'Probation Officer Iii']
Mental Health Specialist Iii -> ['Mental Health Specialist Ii', 'Mental Health Specialist Sr']
Attendant Patient Care Cch -> ['Attendant Patient Care']
Supervisor Of Mechanics Ii -> ['Supervisor Of Mechanics I']
Business Manager Iv -> ['Business Manager I', 'Business Manager Ii']
Administrative Support Vi -> ['Administrative Support Vii', 'Administrative Support V']
Pretrial Officer Ii- Psb -> ['Pretrial Officer I- Psb', 'Pretrial Officer I']
Caseworker Ii Jtdc -> ['Caseworker Jtdc']
Medical Division Chairman Viii -> ['Medical Division Chairman Vii', 'Medical Division Chairman Vi']
Medical Div Chair Viii-Sc -> ['Medical Div Chair Vii-Sc', 'Medical Div Chair Xii-Sc']
Clerk Iv-Cnty Clk/Rod/Sheriff -> ['Clerk V-Cnty Clk/Rod/Sheriff']
Admin Assistant Ii -> ['Admin Assistant I']
Chief Of Human Resources - Rod -> ['Chief Of Human Resources', 'Dir Of Human Resources-Rod']
Admin Assistant Ii-County Clk -> ['Admin Assistant I-County Clerk', 'Admin Assistant I-Cnty Clk/Shf']
Telecommunications Analyst Ii -> ['Telecommunications Analyst Iii', 'Telecommunications Analyst I']
Personnel Analyst Iv -> ['Personnel Analyst Iii']
Administrative Support Iv -> ['Administrative Support Ii', 'Administrative Support Iii']
Clerk Iv Senior Courts -> ['Clerk Iv, Senior Courts']
Management Analyst I -> ['Management Analyst Iv', 'Management Analyst Ii']
Attending Physician X -> ['Attending Physician Xi', 'Attending Physician Xii']
Attending Physician X-Sc -> ['Attending Physician Xi-Sc', 'Attending Physician Xii-Sc']
Program Coordinator Ii-Sheriff -> ['Program Coordinator I-Sheriff']
Assistant Public Defender Ii -> ['Assistant Public Defender Iii', 'Assistant Public Defender I']
Janitor Ii -> ['Janitor Iii', 'Janitor I']
Chief Deputy Clerk Iv -> ['Chief Deputy Clerk I', 'Chief Deputy Clerk Iii']
Manager Iv-Ccc -> ['Manager I-Ccc', 'Manager Ii-Ccc']
Administrative Support V -> ['Administrative Support Vi', 'Administrative Support Vii']
Assistant Public Defender Iii -> ['Assistant Public Defender Ii', 'Assistant Public Defender I']
Laboratory Technician Ii -> ['Laboratory Technician Iii', 'Laboratory Technician I']
Medical Div Chair Xii-Sc -> ['Medical Div Chair Vii-Sc', 'Medical Div Chair Viii-Sc']
Attending Physician Vii-Sc -> ['Attending Physician Viii-Sc', 'Attending Physician Vi-Sc']
Dir Of Environmental Services -> ['Mgr Of Environmental Services']
Highway Engineer Iii -> ['Highway Engineer Iv', 'Highway Engineer V']
Admin Assistant I -> ['Admin Assistant Ii']
Attending Physician Vi -> ['Attending Physician Vii', 'Attending Physician V']
Bookkeeper Viii-Ccc -> ['Bookkeeper Vii-Ccc', 'Bookkeeper X-Ccc']
Attending Physician Viii -> ['Attending Physician Vii', 'Attending Physician Vi']
Attending Physician Viii-Sc -> ['Attending Physician Vii-Sc', 'Attending Physician Vi-Sc']
Attending Physician Sr Xii -> ['Attending Physician Sr Xi', 'Attending Physician Sr X']
Guardian Ad Litem Ii -> ['Guardian Ad Litem Iii', 'Guardian Ad Litem I']
Caseworker Iii Public Grdian -> ['Caseworker Ii Public Grdian']
Manager V-Ccc -> ['Manager Vi-Ccc', 'Manager Vii-Ccc']
Systems Analyst V -> ['Systems Analyst I', 'Systems Analyst Iv']
Psychologist Iii -> ['Psychologist V']
Attending Physician Sr X -> ['Attending Physician Sr Xi', 'Attending Physician Sr Xii']
Attending Physician Sr X-Sc -> ['Attending Physician Sr V-Sc', 'Attending Physician Sr Xi Sc']
Courtroom Manager Iv-Ccc -> ['Courtroom Manager I-Ccc', 'Courtroom Manager Ii-Ccc']
Cashier Ii -> ['Cashier Iii']
Adult Probation Officer- Psb -> ['Adult Probation Officer I- Psb', 'Adult Probation Officer- Psc']
Accountant Iii -> ['Accountant Ii', 'Accountant I']
Deputy Sheriff D2B -> ['Deputy Sheriff Ii']
Associate Judge Circuit Court -> ['Associate Clerk Circuit Court']
Accountant Ii -> ['Accountant Iii', 'Accountant I']
Speech Language Pathologist I -> ['Speech Language Pathologist Ii']
Stenographer V -> ['Stenographer Iv', 'Stenographer Iii']
Vital Records Supervisor I -> ['Medical Records Supervisor I', 'Medical Records Supervisor Ii']
Admin Asst To Comm Brd Of Appl -> ['Adm Asst To Comm Ii Bd Of Apps']
Accountant V -> ['Accountant I', 'Accountant Iv']
Investigator V -> ['Investigator I', 'Investigator V Sa']
Asst Public Defender Superv -> ['Asst Public Defender Superviso']
Attending Physician Senior Vii -> ['Attending Physician Senior V', 'Attending Physician Senior 6']
Administrative Analyst V -> ['Administrative Analyst I', 'Administrative Analyst Iv']
Attending Physician Senior 6 -> ['Attending Physician Senior V', 'Attending Physician Senior Vii']
Senior Database Administrator -> ['Database Administrator']
Residential Jr Field Insp I -> ['Residential Sr Field Insp Iv', 'Residential Sr Field Insp Iii']
Attending Physician Sr Xi -> ['Attending Physician Sr Xii', 'Attending Physician Sr X']
Legislative Coordinator Ii -> ['Legislative Coordinator I']
Systems Analyst Iv -> ['Systems Analyst I', 'Systems Analyst Ii']
Public Health Nurse I -> ['Public Health Nurse Iv', 'Public Health Nurse Ii']
Investigator Ii Ofh -> ['Investigator Ii', 'Investigator Ii Sa']
Medical Technologist Ii -> ['Medical Technologist Iii', 'Medical Technologist I']
Executive Asst Iii Sheriff -> ['Executive Assistant Ii-Sheriff', 'Executive Assistant I -Sheriff']
Executive Assistant Iii -> ['Executive Assistant Ii', 'Executive Assistant I']
Labor Relations Analyst Ii -> ['Labor Relations Analyst']
Attend Physician Sr Vii-Sc -> ['Attend Physician Sr Viii-Sc', 'Attending Physician Sr Vi-Sc']
Guardian Ad Litem Iii -> ['Guardian Ad Litem Ii', 'Guardian Ad Litem I']
Field Technician Ii -> ['Field Technician I']
Attending Physician Vi-Sc -> ['Attending Physician Vii-Sc', 'Attending Physician V-Sc']
Executive Assistant Ii -> ['Executive Assistant Iii', 'Executive Assistant I']
Engineering Assistant Iii -> ['Engineering Assistant Ii', 'Engineering Assistant I']
Storekeeper V -> ['Storekeeper', 'Storekeeper Iv']
Medical Div Chairman Ix -> ['Medical Div Chairman X', 'Medical Div Chairman Xi']
Medical Div Chair Ix Sc -> ['Medical Div Chair X Sc', 'Medical Div Chair Xi Sc']
Clinical Lab Site Supervisor I -> ['Clinical Lab Site Superv Ii']
Medical Assistant -> ['Mechanical Assistant', 'Judicial Assistant']
Epidemiologist I -> ['Epidemiologist Iv', 'Epidemiologist Ii']
Probation Officer Iii -> ['Probation Officer Ii', 'Probation Officer Iii-Y']
Probation Officer V -> ['Probation Officer I', 'Probation Officer Ii']
Deputy Director -> ['Deputy Director Ii', 'Deputy Director Iii']
Data Entry Operator Iii -> ['Data Entry Operator Ii', 'Data Entry Operator Iv']
Nurse Coordinator Ii -> ['Court Coordinator Ii']
Special Procedures Technician -> ['Special Procedures Tech Ii']
Hospital Security Officer I -> ['Hospital Security Officer Iii']
Law Clerk Ii Attorney -> ['Law Clerk Iii Attorney']
Administrative Aide Ccu -> ['Administrative Aide I Ccc', 'Administrative Aide']
Clerk Iv Public Health -> ['Clerk Iv Public Health Afscme']
Revenue Assessment Analyst I -> ['Revenue Assessment Analyst Ii']
Business Manager Iii -> ['Business Manager Ii', 'Business Manager I']
Clerk Iv Public Health Afscme -> ['Clerk Iv Public Health']
Cashier Ii Recorder -> ['Cashier Iii Recorder', 'Cashier I Recorder']
Taxpayer Information Spec I -> ['Taxpayer Information Spec Iv']
Attending Physician Xii-Sc -> ['Attending Physician Xi-Sc', 'Attending Physician Vii-Sc']
Attend Physician Sr Xii Sc -> ['Attending Physician Sr Xi Sc', 'Attend Physician Sr Vii-Sc']
Medical Social Worker Iii -> ['Medical Social Worker Ii', 'Medical Social Worker V']
Residential Junior Analyst -> ['Residential Junior Analyst I', 'Residential Junior Analyst Iv']
Asst Chief Deputy Sheriff -> ['First Chief Deputy Sheriff', 'Chief Deputy Sheriff']
Timekeeperadmin Asst I Ccc -> ['Timekeeper Admin Asst Iv Ccc', 'Timekeeper Admin Asst Ii Ccc']
Manager Iii-Ccc -> ['Manager Ii-Ccc', 'Manager Vii-Ccc']
Manager Vi-Ccc -> ['Manager Vii-Ccc', 'Manager V-Ccc']
Industrial Engineer I -> ['Industrial Engineer Iv', 'Industrial Engineer Ii']
Prof Development Specialist -> ['Youth Development Specialist']
Stenographer Iii -> ['Stenographer Iv', 'Stenographer V']
Computer Operator Iii -> ['Computer Operator Ii', 'Computer Operator I']
Pretrial Officer I- Psb -> ['Pretrial Officer Ii- Psb', 'Pretrial Officer I']
Manager I-Ccc -> ['Manager Iv-Ccc', 'Manager Ii-Ccc']
File Manager I -> ['File Manager Ii', 'File Manager Iii']
General Counsel -> ['General Counsel-Ccc', 'General Counsel-Oiig']
Assistant Administrator -> ['Associate Administrator']
Stenographer Iv -> ['Stenographer Iii', 'Stenographer V']
Probation Officer Ii -> ['Probation Officer Iii', 'Probation Officer I']
Victim Witness Coordntr Iii -> ['Victim Witness Coordinator Ii', 'Victim Witness Coordinator I']
Supervisor I-Sheriff -> ['Supervisor Ii-Sheriff']
Taxpayer Info Specialist Iii -> ['Taxpayer Info Specialist Ii', 'Taxpayer Info Specialist']
Cashier Iii Recorder -> ['Cashier Ii Recorder', 'Cashier I Recorder']
Appeals Analyst Iii -> ['Appeals Analyst Ii', 'Appeals Analyst I']
Janitor Iii -> ['Janitor Ii', 'Janitor I']
Investigator Ii Sa -> ['Investigator V Sa', 'Investigator Ii']
Social Caseworker Iii -> ['Social Caseworker Ii', 'Social Caseworker I']
Budget Analyst Ii -> ['Budget Analyst Iii', 'Budget Analyst V']
Accountant I -> ['Accountant Iv', 'Accountant Ii']
Assistant Public Defender I -> ['Assistant Public Defender Iv', 'Assistant Public Defender Ii']
Cytotechnologist Ii -> ['Histotechnologist Iii']
Attending Physician Sr Ix -> ['Attending Physician Sr X', 'Attending Physician Ix']
Assistant Chief Deputy Clerk I -> ['Assistant Chief Deputy Clk Ii', 'Assistant Chief Deputy Clk Iii']
Aide To The Commissioner I -> ['Aide To The Commissioner Ii']
Assistant Public Defender Iv -> ['Assistant Public Defender I', 'Assistant Public Defender Ii']
Telephone Operator Iii -> ['Telephone Operator Ii', 'Telephone Operator Iv']
Security Officer Ii -> ['Security Officer Iii']
Systems Analyst Ii -> ['Systems Analyst Iii', 'Systems Analyst I']
Window Washer I -> ['Window Washer Ii']
Executive Off Labor -> ['Executive Off, Labor']
Highway Engineer Iv -> ['Highway Engineer Iii', 'Highway Engineer V']
Mis Technician Iii-Ccc -> ['Mis Technician Iv-Ccc']
Mis Analyst Vii Admin-Ccc -> ['Mis Analyst Iii Admin-Ccc', 'Mis Analyst V Admin Ccc']
Driver Iii Ccc -> ['Driver Ii Ccc', 'Driver I Ccc']
Storekeeper Iv -> ['Storekeeper Iii', 'Storekeeper V']
Social Caseworker I- Psb -> ['Social Caseworker Ii- Psb', 'Social Caseworker I']
Public Health Nurse Ii -> ['Public Health Nurse Iii', 'Public Health Nurse I']
Public Health Nurse Iv -> ['Public Health Nurse I', 'Public Health Nurse Ii']
Scientific Officer Ii -> ['Scientific Officer I']
Exec Asst To The Director -> ['Exec Asst To Director']
Adult Probation Officer -> ['Adult Probation Officer- Psc', 'Adult Probation Officer- Psb']
Project Director Iii -> ['Project Director Ii', 'Project Director I']
Program Manager -> ['Ltss Program Manager', '340B Program Manager']
Deputy Chief Of Police -> ['First Deputy Chief Of Police']
Mis System Programmer Iv-Ccc -> ['Mis System Programmer I-Ccc', 'Mis System Programmer Iii-Ccc']
Aide To The Commissioner Ii -> ['Aide To The Commissioner I']
Pharmicist Manager -> ['Pharmacist Manager']
Dietician Iv -> ['Dietician Ii', 'Dietician Iii']
Building Service Worker -> ['Building Service Worker- Cch', 'Building Service Worker- Prov']
Accounts Payable Specialist Ii -> ['Accts Payable Specialist Iii']
Superintendent -> ['Superintendent-Doc']
Attending Physician Sr Vi-Sc -> ['Attending Physician Sr V-Sc', 'Attending Physician Sr X-Sc']
Systems Analyst Iii -> ['Systems Analyst Ii', 'Systems Analyst I']
Central Payroll Processor I -> ['Central Payroll Processor Ii', 'Central Payroll Processor Iii']
Real Estate Indexer I -> ['Real Estate Indexer Ii']
Scientific Officer I -> ['Scientific Officer Ii']
Cashier Iii -> ['Cashier Ii']
Mental Health Officer I -> ['Mental Health Officer Ii']
Deputy Chief Medical Examiner -> ['Chief Medical Examiner']
Chief Medical Examiner -> ['Deputy Chief Medical Examiner']
Caseworker V -> ['Caseworker Iv']
Hearing Officer -> ['Hearing Officer Ii']
Laboratory Assistant Iii -> ['Laboratory Assistant Ii', 'Laboratory Assistant I']
Laboratory Assistant Ii -> ['Laboratory Assistant Iii', 'Laboratory Assistant I']
Project Director Ii -> ['Project Director Iii', 'Project Director I']
Human Resources Specialist -> ['Human Resource Specialist']
Physician-Surgery -> ['Physician Surgery', 'Physician Surgery Sc']
Court Coodinator Iii -> ['Court Coordinator Ii', 'Court Coordinator I']
Vendor & Contract Manager -> ['It Vendor & Contract Manager']
Epidemiologist Senior -> ['Epidemiologist, Senior']
Timekeeper Admin Asst Ii Ccc -> ['Timekeeper Admin Asst Iii Ccc', 'Timekeeper Admin Asst Iv Ccc']
Programmer I -> ['Programmer Iv', 'Programmer Ii']
Expungement Clerk Ii -> ['Expungement Clerk Iii', 'Expungement Clerk Iv']
Tax Examiner V -> ['Tax Examiner Iv', 'Tax Examiner Iii']
Data Entry Operator Ii -> ['Data Entry Operator Iii', 'Data Entry Operator Iv']
Court Coordinator Ii -> ['Court Coordinator I', 'Court Coordinator Iv']
Research Associate -> ['Research Associate Ii']
Programmer Iii -> ['Programmer Ii', 'Programmer I']
Certified Nursing Assistant -> ['Certified Nursing Asst Arnte']
Residential Permit Analyst Iii -> ['Residential Permit Analyst I', 'Residential Permit Analyst']
Administrative Analyst Iii -> ['Administrative Analyst Ii', 'Administrative Analyst I']
Exec Asst To Director -> ['Exec Asst To The Director', 'Exec Asst To Hr Director Rod']
Operating Engineer I -> ['Operating Engineer Iv', 'Operating Engineer Ii']
Management Analyst Ii -> ['Management Analyst Iii', 'Management Analyst I']
Attendant Patient Care -> ['Attendant Patient Care Cch', 'Attendant Patient Care As Req']
Correctional Medical Tech Ii -> ['Correctional Medical Tech Iii', 'Correctional Medical Tech Iv']
Correctional Medical Tech Iv -> ['Correctional Medical Tech Ii', 'Correctional Medical Tech Iii']
Environmental Cont Inspector I -> ['Environmental Cntrl Inspect Ii']
Investigator V Sa -> ['Investigator Ii Sa', 'Investigator V']
Court Coordinator Iv -> ['Court Coordinator I', 'Court Coordinator Ii']
Victim Witness Coordinator I -> ['Victim Witness Coordinator Iv', 'Victim Witness Coordinator Ii']
Manager Vii-Ccc -> ['Manager Vi-Ccc', 'Manager Iii-Ccc']
Rehabilitation Worker Ii -> ['Rehabilitation Worker Iii', 'Rehabilitation Worker I']
Warehouse Records Clerk I Sr -> ['Warehouse Records Clerk I, Sr', 'Warehouse Records Clerk Iv']
Social Caseworker I -> ['Social Caseworker Iv', 'Social Caseworker Ii']
Sanitarian Ii -> ['Sanitarian Iii', 'Sanitarian I']
Resident Jr Analyst Iii -> ['Resid Model Jr Analyst Iii']
Programmer Ii - Assessor -> ['Programmer Iv - Assessor']
Administrative Analyst Iv -> ['Administrative Analyst I', 'Administrative Analyst Ii']
Hris Business Analyst -> ['Business Analyst']
Financial Room Clerk V Ccc -> ['Financial Room Clerk Vi Ccc', 'Financial Room Clerk Iv Ccc']
Assistant Chief Deputy Clk Iii -> ['Assistant Chief Deputy Clk Ii', 'Assistant Chief Deputy Clerk I']
Deputy Member Iii -> ['Deputy Member Ii', 'Deputy Member I']
Medical Div Chairman Xi -> ['Medical Div Chairman Xii', 'Medical Div Chairman X']
Medical Div Chair Xi Sc -> ['Medical Div Chair X Sc', 'Medical Div Chair Xii-Sc']
Chief Med Info Officer -> ['Chief Medical Info Officer']
Chief Medical Info Officer -> ['Chief Med Info Officer', 'Chief Medical Officer']
Bookkeeper Vi -> ['Bookkeeper Iii']
Business Manager I -> ['Business Manager Iv', 'Business Manager Ii']
Assistant Manager Iv-Ccc -> ['Assistant Manager Iii-Ccc', 'Assistant Manager V Ccc']
Food Service Worker I -> ['Food Service Worker']
Taxpayer Info Junior Spec -> ['Taxpayer Info Junior Spec Iv', 'Taxpayer Info Senior Spec Ii']
Victim Witness Coordinator Ii -> ['Victim Witness Coordinator I', 'Victim Witness Coordinator Iv']
Operating Engineer Ii -> ['Operating Engineer Iii', 'Operating Engineer I']
Road Equipment Operator M/M -> ['Road Equipment Operator']
Laboratory Technician Iii -> ['Laboratory Technician Ii', 'Laboratory Technician I']
Occupational Therapy Asst -> ['Occupational Therapist I']
Public Health Educator Senior -> ['Public Health Educator Ii', 'Public Health Educator Iii']
Election Division Supvr I -> ['Election Division Supvr Ii', 'Election Division Supvr Iii']
Caseworker Ii Public Grdian -> ['Caseworker Iii Public Grdian']
Assistant Manager V Ccc -> ['Assistant Manager Iv-Ccc', 'Assistant Manager Iii-Ccc']
Social Caseworker Ii- Psb -> ['Social Caseworker I- Psb', 'Social Caseworker Ii']
Cashier V-Ccc -> ['Cashier Iv-Ccc']
Assistant Manager Iii-Ccc -> ['Assistant Manager Iv-Ccc', 'Assistant Manager V Ccc']

In [55]:
county_pr['Job Title'] = county_pr['Job Title'].replace({
    'Warehouse Records Clerk I  Sr': 'Warehouse Records Clerk I, Sr',
    'Victim Witness Coordntr Iii': 'Victim Witness Coordinator III',
    'Clinical Lab Site Superv Ii': 'Clinical Lab Site Supervisor II',
    'Clinical Laboratory Supv Ii': 'Clinical Laboratory Supervisor II',
    'Executive Off Labor': 'Executive Officer, Labor',
    'Executive Off, Labor': 'Executive Officer, Labor'
})

In [56]:
county_pr['Job Title'].nunique()

2380

In [65]:
county_pr.dtypes

Fiscal Year                     int64
Fiscal Quarter                  int64
Fiscal Period          string[python]
First Name             string[python]
Last Name              string[python]
Bureau                 string[python]
Office                 string[python]
Office Name            string[python]
Job Code               string[python]
Job Title              string[python]
Base Pay                      float64
Position ID            string[python]
Employee Identifier    string[python]
Original Hire Date     datetime64[ns]
Negative Pay Flag                bool
Zero Pay Flag                    bool
dtype: object

In [58]:
county_pr.shape

(234295, 16)

In [57]:
county_pr.duplicated().sum()

np.int64(7)

In [59]:
county_pr = county_pr.drop_duplicates()

In [61]:
county_pr.head()

,Fiscal Year,Fiscal Quarter,Fiscal Period,First Name,Last Name,Bureau,Office,Office Name,Job Code,Job Title,Base Pay,Position ID,Employee Identifier,Original Hire Date,Negative Pay Flag,Zero Pay Flag
0,2016,1,2016Q1,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,20088.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
1,2016,2,2016Q2,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,23436.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
2,2016,3,2016Q3,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,20422.82,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
3,2016,4,2016Q4,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,23904.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False
4,2017,1,2017Q1,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,20745.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False

In [62]:
end_date = pd.Timestamp('2018-06-30')

county_pr['Tenure Years'] = (
    (end_date - county_pr['Original Hire Date']).dt.days / 365.25
)

In [63]:
county_pr['Tenure Group'] = pd.cut(
    county_pr['Tenure Years'],
    bins=[-1, 2, 5, 10, 20, float('inf')],
    labels=['0-2 Years', '2-5 Years', '5-10 Years', '10-20 Years', '20+ Years']
)

In [64]:
county_pr.head()

,Fiscal Year,Fiscal Quarter,Fiscal Period,First Name,Last Name,Bureau,Office,Office Name,Job Code,Job Title,Base Pay,Position ID,Employee Identifier,Original Hire Date,Negative Pay Flag,Zero Pay Flag,Tenure Years,Tenure Group
0,2016,1,2016Q1,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,20088.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False,13.122519,10-20 Years
1,2016,2,2016Q2,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,23436.00,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False,13.122519,10-20 Years
2,2016,3,2016Q3,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,20422.82,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False,13.122519,10-20 Years
3,2016,4,2016Q4,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,23904.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False,13.122519,10-20 Years
4,2017,1,2017Q1,Amrith,Aakre,State's Attorney,1250.0,State's Attorney,1172,Assistant State'S Attorney,20745.80,9510200,6ac7ba3e-d286-44f5-87a0-191dc415e23c,2005-05-16,False,False,13.122519,10-20 Years

In [66]:
county_pr.to_csv(
    r"C:\Users\SEKAR\Desktop\county_payroll_clean.csv",
    index=False
)